### ISSUE TITLE
[planning] design backend cms

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#11]
plan the flow, design comes next. 

this should integrate directly with our postgres database, allowing users to deploy new companies and pages easily. 

In general, we should follow the order of schema.org, since most of the questions that asks we will need to ask for our new clients. Look/feel can be simple as only our internal users will be using it, more of a UI/flow thought process

**Comment by paulchrisluke** [comment]
working on this flow:

https://docs.google.com/spreadsheets/d/1dc1korLAIGK7Cb2j1F3sX2C3fsS7WgosYWRraBfyug0/edit#gid=38506675

**Comment by paulchrisluke** [comment]
may need to plan this out a bit, let me know @atharva3010 

https://www.figma.com/file/d1s8SvSRxoMMDz2QOu5BQeE2/Untitled?node-id=0%3A1

**Comment by atharva3010** [comment]
Okay
