### ISSUE TITLE
CORS error for sayabooking.com

### ISSUE THREAD

**Issue by mort3za** [whynotearth/meredith-core#123]
On sayabooking.com we have CORS error.

Access to XMLHttpRequest at 'https://api.whynot.earth/api/v0/pages/slug/Saya/home/landingpage' from origin 'https://sayabooking.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ctyar** [comment]
Fixed in https://github.com/whynotearth/meredith-core/pull/121
