### ISSUE TITLE
cms, create a page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#13]
https://www.figma.com/file/d1s8SvSRxoMMDz2QOu5BQeE2/Meredith-CMS?node-id=0%3A1

"create a page section" , the hotel info can be ignored for now, this client is simply making blog posts and wants to email them out automatically.

- welcome, log in via social
- create company
- create page
- post via (email, sms, facebook, google)
- second area to upload email lists

**Comment by bamboochow** [comment]
@paulchrisluke do you want me to close this or send in for dev?
