### ISSUE TITLE
Create Prototype for Syncing Exchange Distribution Lists

### ISSUE THREAD

**Issue by StrangeWill** [whynotearth/meredith-core#131]
OK so we're looking to sync distribution lists with Meredith, we need a Windows service/task that can do this for us.

We've eyeballed PowerShell, but from what I've seen/know so far, the PowerShell modules that do this cannot be installed via the PowerShell gallery and only come with Exchange's management tools. So we'd have to execute that on a server with Exchange installed or remote PowerShell into one with them installed.

Other option is to scrape from Outlook via interop, there are some _really_ old docs I've come across (https://docs.microsoft.com/en-us/office/client-developer/outlook/pia/how-to-get-members-of-an-exchange-distribution-list), _ideally_ a .NET Core self-contained console app would be best to start with, we can eyeball making it a service or just calling it from Windows Task Scheduler depending on what we want to do after we have a working prototype. Not sure how well Microsoft Office interop plays with .NET Core is right now (I haven't even tried), if not I guess we can do a .NET 4.x console app.

So far we can just dump it to the console, prove it works. Later we'll want to push it to an API of ours to sync with our list.

-- There may already be some stuff out there that does this, haven't looked at all yet.

**Comment by paulchrisluke** [comment]
This is in backlog as the client has decided they will do a manual export/import into our system once per week instead.
