### ISSUE TITLE
split categories into site specific

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#132]
This is an example of our current database structure. You can see that we have categories as a global table, they should probably be site specific:

https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit?pli=1#gid=0

you can ping @ctyar about database or meredith-core structure questions if needed.

**Comment by ctyar** [comment]
Fixed as part of https://github.com/whynotearth/meredith-core/commit/f7050616a6f542b50326f9261e6038d5aa126a33
