### ISSUE TITLE
setup subdomain configuration

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#133]
when we create a new tenant site, it needs to be a subdomain of foodouken.com:

store1.foodouken.com
store2.foodouken.ocm

each store will have its own categories, products, etc. This task is about automating the subdomain setup portion. We currently use netlify for hosting.

the same situation will occur on browtricks.com, with tenants having their own salon websites as a subdomain:

salon1.browtricks.com

.

It should be noted that we intend to charge the tenants via stripe for these services at some point. (browtricks immediately, foodouken when corona ends)

**Comment by paulchrisluke** [comment]
How do we know which tenants are part of a home page index? https://stagingapi.whynot.earth/api/v0/pages/slug/foodouken/home

**Comment by ctyar** [comment]
We can setup Netlify to rewrite *.foodouken.com to foodouken.com/tenant/* for example.
https://community.netlify.com/t/custom-domains-for-users-with-netlify/3132/4
and from that, we can use the tenant slug to talk to API.

**Comment by paulchrisluke** [comment]
@atharva3010 is the above something you can implement?

**Comment by paulchrisluke** [comment]
So, I was spekaing to @mort3za , and he made a good point that for scale, a directory for each tenant may seem easier to manage long term than a sub domain, which I agree with... and if we are going to make that decision, now is the time to do it I assume.

One thing to consider is that browtricks intends to allow people to upgrade to an Enterprise level accoutn (more expensive per month), which allows them to use a custom domain. Would using subdomains make more sense in this case @ctyar ?

**Comment by atharva3010** [comment]
I didn't quite understand this: _"a directory for each tenant may seem easier to manage long term than a sub domain"_

**Comment by mort3za** [comment]
@atharva3010 
`/tenant/tenantSlug/...`

**Comment by paulchrisluke** [comment]
we are closing this to do sub directory slugs rather than sub domains for data tracking at scale.
