### ISSUE TITLE
add ecommerce "products" module

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#134]
For foodouken.com each subscriber site will sell MENU products. We have an example of that json below.

Instead of nesting all this json in our current `pages` table, we need to create a new module to contain this product information. this has the potential to grow to a full ecommerce module for selling and shipping physical products, keep that in mind.

```
{
    "products": [{
        "price": "2.00",
        "currency": "USD"
    }]
}
```

**Comment by paulchrisluke** [comment]
we should probably architect this in a similar way we did the moduleHotel, or any standard ecommerce/delivery module. @StrangeWill do you have any design input? Foodouken is a food delivery app, currently at https://foodouken.com

We are doing a simple form for now, but will probably link in stripe features down the road.

**Comment by StrangeWill** [comment]
Depends on what we want for products, though a simple product table under an e-commerce module would probably work fine. We can split that out into more complex stuff later if needed.

**Comment by ctyar** [comment]
A basic `Product` entity would need these properties:
```
TenantId
CategoryId
Name
Description
ImageId
Price
Currency
```
In first phase, we add/edit/delete the products directly from DB and we just need to provide a readonly API

**Comment by paulchrisluke** [comment]
@ctyar how do we reference product images? Can I add images to the images table and reference the product ID?

**Comment by ctyar** [comment]
Yes, in `images` table you have to set the `ProductId` and `Discriminator`.
`Discriminator` should be `Product`.

**Comment by paulchrisluke** [comment]
checking my work here. Test api:

https://stagingapi.whynot.earth/api/v0/pages/slug/bang-bang-bakery-cafe/cakes-and-cookies

I'm expecting to see cakes and cookies, which I've added in the product table here:

![image](https://user-images.githubusercontent.com/5694308/79245617-8a668e00-7ea2-11ea-88b0-ac5cd352921c.png)

I've added images here:

![image](https://user-images.githubusercontent.com/5694308/79245712-a9fdb680-7ea2-11ea-84e1-e21098a5b5e3.png)


but I am not seeing my products reflected in tha api call?

**Comment by ctyar** [comment]
It should be fixed now.
One thing though you haven't set the `Discriminator` column in the `Categories` table to `ProductCategory`.

**Comment by paulchrisluke** [comment]
looks good, example endpoints here:

https://stagingapi.whynot.earth/api/v0/tenant/1/categories
https://stagingapi.whynot.earth/api/v0/tenant/1/categories/16/products

Will write an issue to get frontend to refactor foodouken
