### ISSUE TITLE
CMS - Create CRUD endpoints for Posts

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#141]
Your mission, should you choose to accept it: 

# Create CRUD endpoints for the entity `Post`

![image](https://user-images.githubusercontent.com/5694308/78654702-2286d500-78ef-11ea-8704-f41d1ef88185.png)

Post entity includes: 

- Category
- Headline (Maximum length: 50)
- Description (Maximum lenght: 500) 
- Price 
- Event Date 
- Image (https://github.com/whynotearth/meredith-core/issues/109)

There will be 3 different forms depending on the category chosen, each containing these information
![image](https://user-images.githubusercontent.com/5694308/78660963-32ef7d80-78f8-11ea-9bd2-8d12f5c2d9dc.png)

Regular Post: 
- Headline 
- Description
- Image

Answers at a glance: 
- Headline 
- Description 

Event Post: 
- Headline
- Description
- Price
- Event Date 
- Image

Post content and image will be placed in a article template preview in the next step
![image](https://user-images.githubusercontent.com/5694308/78659716-2833e900-78f6-11ea-8e08-5a6de855d479.png)

Design File
The specs for the page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

**Comment by ctyar** [comment]
Implemented everything but the images
