### ISSUE TITLE
add category id to page 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#15]
@atharva3010 is using category to dynamically change the form based on the page category type. In our database I see category ID but its not reflected in the link:

![image](https://user-images.githubusercontent.com/5694308/60359281-d5daa900-9a02-11e9-8d8b-9e9f0e715a1f.png)

https://stagingapi.whynot.earth/api/v0/pages/slug/vkirirom/Bungalow

I added category ID to the "name" field for now since we aren't using it

**Comment by StrangeWill** [comment]
Added in 37704cce768d31cc0a7f1b3b728e4879451c26f2
