### ISSUE TITLE
add multi language support to public

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#154]
Right now, we have language tables in our hotel module. We need to add the same language tables to our public `pages` table so that all of our pages support multi language i89n stuff. @ctyar I am thinking this will be a good one for new contributors if you add a little more detail to this issue we can probably chunk that out to new contributors over time?

**Comment by paulchrisluke** [comment]
@KennethA1000 possibly a good one for you if you have time.

**Comment by pjanicked** [comment]
Is @KennethA1000 working on this? If not, would like to contribute.

**Comment by paulchrisluke** [comment]
@pjanicked he has not started yet, you're welcome to pick it up. Thank you! We have a discord we use like a work slack if you'd like to join or have quetsions: https://discord.gg/Rdfk9kg

**Comment by KennethA1000** [comment]
Yes, I am not doing anything on this one.

**Comment by pjanicked** [comment]
Hi @paulchrisluke , can you assign me this issue?
