### ISSUE TITLE
endpoint to provide distribution lists for group selection in cms

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#162]
after the volkswagen admin uploads his email lists with groups assigned, he will expect to see a list of all distribution groups.

He will also expect to select these lists from a dropdown in the "to:" section as he types. *we were planning on doing a gmail style suggestion as you type thing. Is that hard? 

Love,
Chris

**Comment by ctyar** [comment]
Fixed in https://github.com/whynotearth/meredith-core/commit/37a912d87c51fee3f3311b91e342b1ad62885242
