### ISSUE TITLE
Need endpoints for user profile GET and PUT

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/meredith-core#174]
We use the user's name throughout our app. In the settings page, we can edit that name too.

![image](https://user-images.githubusercontent.com/34229217/81537515-f5fd2780-938a-11ea-93c4-545df3eaf176.png)

So we need two new endpoints for that 
1) to get the profile info, i.e. name, email, etc.
2) to let them update their profile(name...)

**Comment by paulchrisluke** [comment]
Can we show email instead of name so we don't need to add another endpoint?

**Comment by atharva3010** [comment]
Yeah, actually I don’t know if email is editable, and in either case, we need a GET and a PUT endpoint.
