### ISSUE TITLE
track billing info stats

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#183]
1. we need to track the below info. This should come from Sendgrids api.
2. provide GET endpoints for the frontend team to style this data
3. (preferred, optional), integrate with stripe invoicing to auto send a bill to billing contact monthly

data points we need:

-  monthly active users, the number of recipients who have opened 1 email in the month.
-  of emails sent monthly

**Comment by bemaxima** [comment]
Is it specifically for the Volkswagen module? or It is a general module for the entire system in which one of the consumers is the Volkswagen module. @paulchrisluke

**Comment by paulchrisluke** [comment]
General module 👍🏾

**Comment by paulchrisluke** [comment]
@ctyar how do I see these stats?

**Comment by ctyar** [comment]
GET `/api/v0/emails/{companySlug}/stats`
