### ISSUE TITLE
add authentication for cms

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#19]
@atharva3010 will need endpoints too, base cms design here: https://www.figma.com/file/d1s8SvSRxoMMDz2QOu5BQeE2/Meredith-CMS?node-id=95%3A0

need to be able to create and edit pages as MVP.

**Comment by paulchrisluke** [comment]
I think identity has been added, @atharva3010 needs endpoints, do we need to add these to the api @StrangeWill ? 

CMS found here:

https://www.figma.com/file/d1s8SvSRxoMMDz2QOu5BQeE2/Meredith-CMS?node-id=160%3A244

**Comment by StrangeWill** [comment]
@atharva3010 is wired up to identity, but I do need to add oauth for Facebook and Google, I also need to ponder how to do that workflow in the context of an SPA.

**Comment by StrangeWill** [comment]
OAuth has been pushed in #30, just need to figure out how we want to handle flow (eg: do we redirect back to where the app requests, or do we self-close?)
