### ISSUE TITLE
add CRUD endpoints for entities in public module

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/meredith-core#191]
https://www.figma.com/file/48dgLg97h5BxdmCkDgrMof/Meredith-Core-ER-Diagram?node-id=35%3A53160

These modules/tables should already be built. We need to ensure we have endpoints as well so the frontend team can build our cms.

Current:
https://stagingapi.whynot.earth/index.html

**Comment by paulchrisluke** [comment]
limiting this to  the Sign up Flow and Menu (categories/menu items).

added backlog note for other items here:

![image](https://user-images.githubusercontent.com/5694308/82685678-c8638880-9c7e-11ea-803e-bd862b15c960.png)
