### ISSUE TITLE
GET endpoint for Client list

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/meredith-core#192]
The data should return a paginated response containing a list of contact objects that are alphabetically sorted by a key "name" and grouped by its first letter.

Since the contact list has virtually no limit to how big it can grow, we don't want to do all that compute on the client-side as most of the users would be using the app on their mobile devices. Hence, letting the backend handle it is a good idea.
On the frontend part, @sally may need to call this paginated endpoint with infinite scrolling.

Please refer this screenshot to get a better idea:

![image](https://user-images.githubusercontent.com/34229217/82786606-8dca3d80-9e82-11ea-868b-069027e421e3.png)

**Comment by ctyar** [comment]
@atharva3010 you can access get this data now
GET `/api/v0/companies/{companySlug}/tenants/users`
