### ISSUE TITLE
Add support to accept image as param in case of product, productCategory and tenant endpoints

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/meredith-core#202]
Right now, we cannot send an image as payload in case of product, productCategory and tenant endpoints. We need to support sending a string (i.e. link of cloudinary hosted image), in the payload of these models.

![image](https://user-images.githubusercontent.com/34229217/84524908-5835a900-acf8-11ea-8f01-a6f8ccb1f1a8.png)
![image](https://user-images.githubusercontent.com/34229217/84524926-61bf1100-acf8-11ea-8544-69c11bca43b2.png)
![image](https://user-images.githubusercontent.com/34229217/84524972-77343b00-acf8-11ea-8d08-62f959acfcb6.png)

**Comment by kevinkhao** [comment]
https://github.com/whynotearth/meredith-core/pull/203
