### ISSUE TITLE
Question: How to save user info in case of OAuth

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/meredith-core#218]
Right now we use the register endpoint in the checkout flow at foodouken, to create password-less accounts.

Since we are now shifting to using OAuth for that, we need a place to save all this data to the user account, since user’s details are used for the reservation. Below are the details we pass when registering via the /register endpoint:
```
{
  "email": "string",
  "name": "string",
  "phoneNumber": "string",
  "address": "string",
  "googleLocation": "string",
  "tenantSlug": "string"
}
```
I want to know, where should we save these details in case of OAuth.

**Comment by StrangeWill** [comment]
This is going to be a long one:

- Registration includes other platforms, what does this look like for Vkikirom, who don't use any of these fields as part of registration?
- What about users straddling multiple tenants? We never siloed users into each tenant so what if I need a different tenant account? What about a different tenant account on another Meredith powered platform?
- Google location seems to be a temporary thing, something that exists at-checkout and should be done on the order, not on the user, which will change later (same with address, phone number, etc. these are all contact details that can change/different places I'll want to deliver to).


Ideally: none of this should have anything to do with registration and everything to do with order completion.

**Comment by paulchrisluke** [comment]
@StrangeWill 
`Registration includes other platforms, what does this look like for Vkikirom, who don't use any of these fields as part of registration? Registration should stay platform-agnostic.
`

Eventually we will update vkirirom to match foodouken/browtricks/the rest of our stuff. Currently they checkout is already pretty wonk, and we let them know it was broken. They do not want to "unbreak" it right now, so the site is mostly a visual portfolio piece. We should update the flow at some point, and will.

`What about users straddling multiple tenants? We never siloed users into each tenant so what if I need a different tenant account? What about a different tenant account on another Meredith powered platform?`

Users own tenants like subscribtion services. A single user can be a tenant of any meredith core powered platform. This follows google payments, and is demonstrated in figma prototype here:
https://www.figma.com/proto/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=4040%3A504&viewport=112%2C593%2C0.1778191477060318&scaling=min-zoom

![image](https://user-images.githubusercontent.com/5694308/85104217-64f35900-b232-11ea-9c8b-419d35d13632.png)
![image](https://user-images.githubusercontent.com/5694308/85104266-7d637380-b232-11ea-9239-54005af0a35d.png)

https://pay.google.com/gp/w/u/0/home/activity

Long term we will hide browtricks from foodouken users and vice verse, but I imagine a better plash page which says "here's all our services". This is similar to how you have a single google account with youtube service, maps, etc.

`Google location seems to be a temporary thing, something that exists at-checkout and should be done on the order, not on the user, which will change later (same with address, phone number, etc. these are all contact details that can change/different places I'll want to deliver to).`

agree

`For future knowledge for data that does make sense in being part of a user profile: flow is the same for both registration + user account management with oauth or not. You should register the user then post any additional metadata collected to the user's profile separately to keep the registration endpoint to the minimum required to complete registration and not to include things required for other workflows. We should not be trying to customize the registration endpoint per-client or possibly breaking backwards compatibility.`

Also agree, all of our app registrations are the same data collected and steps. After the user account is created, we push them to make a service (like setup the browtricks site or foodouken site), but this is service setup not part of the user auth flow.

**Comment by StrangeWill** [comment]
> @StrangeWill
> `Registration includes other platforms, what does this look like for Vkikirom, who don't use any of these fields as part of registration? Registration should stay platform-agnostic. `
> 
> Eventually we will update vkirirom to match foodouken/browtricks/the rest of our stuff. Currently they checkout is already pretty wonk, and we let them know it was broken. They do not want to "unbreak" it right now, so the site is mostly a visual portfolio piece. We should update the flow at some point, and will.

There is no reason to break backwards compatibility, a better division of responsibilities would prevent breaking it. It's really handy for us to kind of shit on vkirirom but that's become our go-to, how do we handle the platforms breaking each other when our default is to break that compatibility?


> `What about users straddling multiple tenants? We never siloed users into each tenant so what if I need a different tenant account? What about a different tenant account on another Meredith powered platform?`
> 
> Users own tenants like subscribtion services. A single user can be a tenant of any meredith core powered platform. This follows google payments, and is demonstrated in figma prototype here:
> https://pay.google.com/gp/w/u/0/home/activity
>
> Long term we will hide browtricks from foodouken users and vice verse, but I imagine a better plash page which says "here's all our services". This is similar to how you have a single google account with youtube service, maps, etc.

Yeah this kind of rolls back into wanting users to be siloed (so basically you'd sign up once on each platform, we'd have less tracking, no SSO, etc.), the main reason we stopped was that there is a significant amount of work to make Identity Framework silo properly.
 
> `Google location seems to be a temporary thing, something that exists at-checkout and should be done on the order, not on the user, which will change later (same with address, phone number, etc. these are all contact details that can change/different places I'll want to deliver to).`
> 
> agree
> 
> `For future knowledge for data that does make sense in being part of a user profile: flow is the same for both registration + user account management with oauth or not. You should register the user then post any additional metadata collected to the user's profile separately to keep the registration endpoint to the minimum required to complete registration and not to include things required for other workflows. We should not be trying to customize the registration endpoint per-client or possibly breaking backwards compatibility.`
> 
> Also agree, all of our app registrations are the same data collected and steps. After the user account is created, we push them to make a service (like setup the browtricks site or foodouken site), but this is service setup not part of the user auth flow.

We can collect data up-front that is part of a multi-endpoint flow that is still a single "step" as far as the user is concerned, the API and the SPA doesn't have to match 1:1 (and really really shouldn't most of the time), the API should keep things abstracted while the app is allowed to be a lot more tailored to user experience.

**Comment by ctyar** [comment]
@atharva3010 you can send those info to `/api/v0/profile`
