### ISSUE TITLE
Re-login after log out

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/meredith-core#238]
On Foodouken, we currently have a re-login feature where users are automatically logged into previous accounts after log out. 

The steps to reproduce this: 
1. Log into foodouken using FB or Google https://staging.foodouken.com/auth/login
2. Log out of the account https://staging.foodouken.com/settings
3. Choose method you previously logged in with: https://staging.foodouken.com/auth/login
4. User is automatically logged into to previous account. 

# Question 
What if someone logged out because they wanted to log into a different gmail or facebook account?

# Screenshots
https://staging.foodouken.com/auth/login After Log Out 
![unknown (4)](https://user-images.githubusercontent.com/14948326/86036491-277ba080-ba68-11ea-8b22-012bdfb3e08f.png)

https://staging.foodouken.com/auth/login Automatically logged back in 
![unknown (5)](https://user-images.githubusercontent.com/14948326/86036504-2ea2ae80-ba68-11ea-92e3-593c21433b34.png)

Response of last ping (testing using Google ): 
```
{"id":43,"userName":"bamboo.chow@gmail.com","isAuthenticated":true,"loginProviders":["Google"]}
```

Response of last ping ( testing using Facebook ): 
```
{"id":50,"userName":"bamboo.chow@hotmail.com","isAuthenticated":true,"loginProviders":["Facebook"]}
```

**Comment by ctyar** [comment]
@bamboochow I'm not sure I understand what's the issue here
after this step:
`3. Choose method you previously logged in with: https://staging.foodouken.com/auth/login`
You have logged in again. Do you expect to see the Google select account and enter the password again?

**Comment by paulchrisluke** [comment]
Example:

If you have multiple gmail accounts and you use gmail1 to create your first store, log out. but want to make a new user with gmail2, you are unable to sign in as gmail2 because you are not prompted to choose the gmail account if you have multiple accounts.

She's expecting something like this:

![image](https://user-images.githubusercontent.com/5694308/86091810-b7f0ca00-bad6-11ea-93b9-b8a5792b1eca.png)

**Comment by ctyar** [comment]
Fixd in https://github.com/whynotearth/meredith-core/commit/d0851190c0ab84cb90479662d83b34393be03c2a
