### ISSUE TITLE
provide hls integration endpoints for front end team

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#24]
SOAP API?

[HLS XML API - Certification Process.pdf](https://github.com/whynotearth/meredith-core/files/3395254/HLS.XML.API.-.Certification.Process.pdf)
[HLS XML API - OTA Partner - v1.2.7.pdf](https://github.com/whynotearth/meredith-core/files/3395255/HLS.XML.API.-.OTA.Partner.-.v1.2.7.pdf)

**Comment by StrangeWill** [comment]
@paulchrisluke I need credentials.

**Comment by paulchrisluke** [comment]
I think I sent these in discord, if not I'll dig them up and send again. Also placing in vkirirom project. Need to start worrying about this when they start getting a stripe account setup, which could take some time. Shinta mani wild is a higher priority right now.

**Comment by paulchrisluke** [comment]
closing this, may not need hls integration as we have moved to forms without it for some time now. Will keep this around in case we need docs again
