### ISSUE TITLE
Brow Tricks Sign Up - Setting Business Hours

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/meredith-core#248]
# Set Business Hours 
In setting up a business/tenant for BrowTricks, users set up their business hours here 
![image](https://user-images.githubusercontent.com/14948326/86580110-76659080-bfa8-11ea-9181-d415df7fa92d.png)

For all days of the week, users must be able to: 
- Set Opening / Closing Hours by hours and minutes 
- Set day as closed 

# Business Hours 
The business hours will be displayed and editable in the "Business Hours" page of their settings. 
![image](https://user-images.githubusercontent.com/14948326/86581161-ede7ef80-bfa9-11ea-8f5e-e3bc4b536cf2.png)

# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/m8JgvnHpgPmGq8Bm2iAf1a/Brow-Tricks?node-id=709%3A10179)

You can find the designs for this issue in the "Tenant CMS" Page

**Comment by ctyar** [comment]
We already have this functionality
