### ISSUE TITLE
Footer not showing tenant information

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/meredith-core#258]
The footer should be showing tenant location, phone number and more.
However, that information is currently not displayed 

![image](https://user-images.githubusercontent.com/14948326/86510752-ba2b8f00-be1c-11ea-85c1-53b56273497a.png)

# Design
![image](https://user-images.githubusercontent.com/14948326/86510784-18587200-be1d-11ea-8a27-389115a39e46.png)

# Affected Code
THIS IS CODE FOR THE FOOTER 
https://github.com/whynotearth/foodouken.com/blob/staging/src/components/Footer.vue

# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=1245%3A57965)

You can find the designs for this issue in the "Tenant Site" Page of Figma

**Comment by ctyar** [comment]
@bamboochow  I've added these fields to Tenant but we probably need to edit the Tenant form to let the user add/edit them

**Comment by paulchrisluke** [comment]
made design issue here, will follow through on front end too https://github.com/whynotearth/foodouken.com/issues/338
