### ISSUE TITLE
stripe integration and payment process

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#26]
immediate and future scheduled payments

## Bensley - 

Booking:
50% immediate upon booking 50% 30 days before arrival. If under 30 days, full amount due upon booking. 

Cancellation:
If cancelling, 91 days before, no charge. If 90-31 days before, 50%. 30 days or less 100$ is charged.

Tax: 10% VAT

Addons:
Transportation, helicopter ride. Charged immediately (added to total)

```
4. PAYMENT TERMS
Payment shall be made as follows:    - 50% of the total amount of the stay is required at time of booking.- 50% is to be received at least 30 days before arrival.    Failure to do so may result in the booking cancellation without notice.
```
```
Cancellations or amendments must be made by written notification only and will not be accepted by telephone call.The conditions are:
- Up to 91 days before arrival: no charge.
- From 90 to 31 days before arrival: 50% of the total stay will be charged.    - 30 days or less before arrival and no-show: 100% of the total stay will be charged.
```

## vKirirom

Booking: 
100% charged day of checkout.

Cancellation:
If cancel less than 24 hours before we charge 50 percent.

Tax: 10% VAT

Addons:

Catered BBQ, kerioke rentals, transportation, all added the total invoice and charged at the same time.

## both

May want to consider an adjustment option. Both Kirirom and Bensley offer discounts. Kirirom if you are a large group and want some sort of custom package. Bensley for friends.

**Comment by paulchrisluke** [comment]
Bensley also has a 3 day minimum  stay requirement

**Comment by StrangeWill** [comment]
I'll probably be chopping this up into multiple requests:
- Stripe payments
- Hotel policies (payments/cancellation/etc)
- Addons

**Comment by StrangeWill** [comment]
Addons: #34 
Policies: #33

**Comment by paulchrisluke** [comment]
fyi bensley/shinta mani wild is not active, so only need to consider vkirirom for now
