### ISSUE TITLE
Promotion 

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/meredith-core#260]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=2887%3A1)

For the design and the flow, go to the "Tentant CMS" page

# Promotions Page
This is a promotions page that applies a discount to all products store wide. 
The functions in this page include: 
- Store-wide Discount Input: this is a field that accepts whole numbers as percentages, will apply discount to all store items. For example, user inputs "10" for percentage, all item prices are now {original price - (original price x 0.1)} 
- Activate toggle: Starts promotion when active, ends promotion when when inactive
![image](https://user-images.githubusercontent.com/14948326/87406616-22335f80-c5eb-11ea-90e8-892905282530.png)

# Customer View 
On start of promotion, viewers on store site will see all product item labeled with "{percentage}% Off" 
- Tag showing amount of percentage off 
- Original price, crossed out 
- Promotion Price 

![image](https://user-images.githubusercontent.com/14948326/87381066-0c5b7580-c5be-11ea-9c3e-cf2443c84329.png)
![image](https://user-images.githubusercontent.com/14948326/87406646-2fe8e500-c5eb-11ea-9625-ce959c8e45cd.png)

**Comment by paulchrisluke** [comment]
@ctyar just a heads up, this applies pricing to every product in the store. The front end team will need to know products are discounted to show the original and discounted price on the product page

ex. 20% off! ~~$10~~ $8

**Comment by ctyar** [comment]
API: PATCH `/api/v0/companies/{companySlug}/tenants/{tenantSlug}`
