### ISSUE TITLE
[BUG] Client archive and client put endpoints doesn't work properly

### ISSUE THREAD

**Issue by abdullahcalisir12** [whynotearth/meredith-core#267]
# Location

Where in the app did you encounter the bug?

# Expected Behavior
When I archive client it returns successful code but it still shows at the client list.
When I update client info it still returns me old infos

What did you expected would happen?

# Actual Behavior

What happened instead?

# Browser, Device, OS and Versions

What browser, device, and operating system were you on? What versions? e.g. Safari 13, iPhone 11, iOS 13.0

# Steps to Reproduce

What are the steps to reliably reproduce the bug? e.g.

# Screenshots/casts

Provide any additional screenshots/screencasts that you think would help explain/treat the problem.

# Additional Context

Provide any additional notes here that you think would help explain/treat the problem.

**Comment by ctyar** [comment]
Fixed in https://github.com/whynotearth/meredith-core/commit/5fc979db9dced517bd3413ecfc495d1e8706ae37
