### ISSUE TITLE
support facebook authentication

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#285]
I think we already have this? maybe there is a bug

Users can use their facebook account as a way of signup 
![image](https://user-images.githubusercontent.com/14948326/91629569-4957bc00-e9f4-11ea-87ba-fa9a79300f58.png)

**Comment by bamboochow** [comment]
@paulchrisluke there was some sort of verification error either location or identity that facebook was not happy about and did not allow

**Comment by paulchrisluke** [comment]
this is working, app was in dev mode on fb. resolved
