### ISSUE TITLE
Password reset text for both text and email

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#297]
# Subject Line:
"{{username}}, we've made it easy to get back on {{Company}}"

# Body:

https://res.cloudinary.com/whynotearth/image/upload/v1600846670/BrowTricks/static_v2/logo-round-wbg_oo659o.png

Hi {{username}},

Sorry to hear you're having trouble logging into {{Company}}. We can help you get straight back into your account.

[button]Log in as {{username}}[/button]   (sends to /reset-password)
   
https://res.cloudinary.com/whynotearth/image/upload/v1600846670/BrowTricks/static_v2/logo-round-wbg_oo659o.png

# Example
![image](https://user-images.githubusercontent.com/5694308/95326586-06c7b000-08cd-11eb-8362-4c1f6fc21ae5.png)

**Comment by ctyar** [comment]
This needs a non HTML version in case we had to text them instead of email

**Comment by mort3za** [comment]
[reset-password.zip](https://github.com/whynotearth/meredith-core/files/5346339/reset-password.zip)

![image](https://user-images.githubusercontent.com/510242/95434114-bc424400-095d-11eb-943c-3e3aeaef3b0b.png)

**Comment by paulchrisluke** [comment]
@ctyar my first name is doubled in the email subject line and buttoN?

![image](https://user-images.githubusercontent.com/5694308/95544188-a21f6900-0a24-11eb-84c8-ed9132bae5ef.png)

**Comment by paulchrisluke** [comment]
nevermind I had two names in my user profile @ctyar
