### ISSUE TITLE
forgot password is not sending emails, instead I get texted a random series of characters

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#299]
use 10 minute mail
make new account
logout
press forgot password
enter email
no email is recieved, the following was texted to me:

2srzefJlEw%2bjRCU9aVBl1HbMLJnKD01CYMGAbXxAxzbiq8U47tvTx1FtvpHBmX16k6iGNyYNkxR806UOMhBIaSQ%3d%3d

**Comment by ctyar** [comment]
If you don't have a confirmed email and you confirm your phone number we send a text instead of and email
and the text contains 
```
"Sorry to hear you're having trouble logging into {company}. We can help you get straight back into your account. {url}
```

**Comment by paulchrisluke** [comment]
But it doesn't say that, it's gibberish
