### ISSUE TITLE
add bed type "large twin"

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/meredith-core#31]
what are the current bed types and numbers? 

we need

twin
large twin
double
queen
king

**Comment by StrangeWill** [comment]
```King = 0
Queen = 1
Twin = 2
Single = 3
LargeTwin = 4
Double = 5
```

**Comment by StrangeWill** [comment]
e64416aeac2e1588020e1ca8f5d922453cbaf598

**Comment by paulchrisluke** [comment]
add king please, 6

**Comment by StrangeWill** [comment]
Ideally: we shouldn't re-open tickets that have had their original scope completed.

**Comment by StrangeWill** [comment]
King is already 0, I somehow screwed up posting it.

**Comment by StrangeWill** [comment]
Oh no, Github just didn't like "King = 0" being on the same line as triple backticks, it was there.
