### ISSUE TITLE
invalid token on sms pmu form use

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#310]
login
create pmu form
create client with valid usa number
click pmu forms and send via text
open text message, recieve error ïnvalid token:

```
fetch("https://stagingapi.whynot.earth/api/v0/authentication/tokenlogin", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en",
    "content-type": "application/json",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "http://localhost:8080/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"token\":\"OZYQPOTQBDZR2WKLQFAUID43P2UQDQFE\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});
```

**Comment by mort3za** [comment]
I tested this myself, I got a link and it worked.  
These links have a one time login code, is it possible that you have opened it twice? @paulchrisluke

**Comment by mort3za** [comment]
I'll push a fix to prevent showing error if you were logged in, this makes refreshing page possible.

**Comment by paulchrisluke** [comment]
![Screenshot_20201016-222207](https://user-images.githubusercontent.com/5694308/96277264-375ec680-0ffe-11eb-8716-151592746846.png)
These were new texts, just tested again same error in private. But yea maybe since I'm texting to my own number
