### ISSUE TITLE
Add "keywords" column to the pages db

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#42]
So we can target keywords for each page for SEO structured data. 

Eventually I would imagine the cms would handle this, applying "title" to the title meta data, or changing the schema from "event" to "article" depending on category selection. Is there an existing generator we could leverage?

https://technicalseo.com/tools/schema-markup-generator/

**Comment by StrangeWill** [comment]
Actually going to remove this until there is some more clarification on this:

Keywords are usually just a list of words, they can be structured in a few different ways depending on how we want to handle things (eg: best to keep a table of keywords and link them to a page).

> Eventually I would imagine the cms would handle this, applying "title" to the title meta data, or changing the schema from "event" to "article" depending on category selection. Is there an existing generator we could leverage?

However, this makes absolutely no sense in the context of a keyword list. So the requested feature is a bit unclear.

**Comment by StrangeWill** [comment]
OK, standard keywords.

**Comment by paulchrisluke** [comment]
@KennethA1000 last tag for tonight, another good one. Each one of these is adding extra data to our already existing structures

**Comment by ctyar** [comment]
Fixed in https://github.com/ctyar/meredith-core/commit/6db826e3c91dc3741817ca415be121c8c7ff140d
