### ISSUE TITLE
Adding cards to a page 500 error's the api

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#49]
(staing db)

api url: https://stagingapi.whynot.earth/api/v0/pages/slug/shintamaniwild/Wild-tents

I added the following card, and assigned pageID 68, which is the page ID for `Wild-tents`
![image](https://user-images.githubusercontent.com/5694308/63666166-a5439f80-c7f8-11e9-8ad8-f52b0ad8759b.png)

Once added, the api response changes to 500:
![image](https://user-images.githubusercontent.com/5694308/63666192-b8566f80-c7f8-11e9-8457-0468965c405a.png)

If I remove the card entry in the database, the error goes away.

**Comment by StrangeWill** [comment]
https://rollbar.com/WhyNotEarth/Meredith/items/44/

`Exception: Card type 1 not mapped.`

Only "CardType" is "0" which is "Card"

**Comment by paulchrisluke** [comment]
I'm an idiot.
