### ISSUE TITLE
change bed type to text instead of number

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#5]
so I can write "king" :)

**Comment by StrangeWill** [comment]
It's an enum, I got some options:

- Make it a DB table, at which point you'll need to put the integer from the `BedTypes` table.
- Make it a string which leads to:
  - People being able to typo records (or make them inconsistent)
  - More overhead in searching
  - Harder to do programmatic things
- Keep it an enum

**Comment by paulchrisluke** [comment]
Make it a DB table, at which point you'll need to put the integer from the BedTypes table.

we can do this

**Comment by paulchrisluke** [comment]
updated and shipped
