### ISSUE TITLE
No "Order" property on stories

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#51]
![image](https://user-images.githubusercontent.com/5694308/65224128-c5f7d000-daec-11e9-8024-37b572460ca9.png)
Order property is included in the lightroom stories within the database. 

However, within the api, the order property is not showing up for stories within the API.
https://stagingapi.whynot.earth/api/v0/pages/slug/shintamaniwild/Wild-tents

Individual example: 
{"blur":"2px","content":"Filled with butterfly art with the centrepieces being two colour paintings by famous UK artist Kate Spencer, this tent is delightful.","ctaText":"The Butterfly Tent","ctaLink":"","image":"https://res.cloudinary.com/ddwsbpkzk/video/upload/v1567843472/Shinta%20Mani%20Wild/Wild%20Tent/The%20Butterfly%20Tent/The_Butterfly_Tent_-_Story_-_3_cyo6en.mp4","posterUrl":"","type":"story-card"}

**Comment by paulchrisluke** [comment]
I think we opted to not use order in this case... @StrangeWill @mort3za ? If we are not using it, I can close this ticket and backlog another one to maybe rename the column or use it for something else

**Comment by StrangeWill** [comment]
Yeah, so far exposing ordering has just resulted in it being used to _disorder_ things and group them, if we need to do that we should properly do it, otherwise we just break ordering (and that'll break in a CMS).

**Comment by paulchrisluke** [comment]
Should we just rename order to... category , group, tag...? I’ll need to
think

**Comment by StrangeWill** [comment]
Probably just add the ability to tag stories, and let you run with tags, and have you fix ordering.

Though arguably the entire concept of a "story" doesn't even work anymore, we're not doing stories, but that's a larger question of what do we do with that.
