### ISSUE TITLE
add actual blog post date to blog posts

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#57]
provide a date endpoint for page posting. Right now its statically set to July 5 for all blog posts.

it should be whenever the page was created in the DB. @StrangeWill can we provide timestamps for page creation?

**Comment by paulchrisluke** [comment]
also, while we are at it, may as well add "last edited" date column , just in case we need that in the future

**Comment by dotnetphenom** [comment]
I will make this my first contribution :)

**Comment by paulchrisluke** [comment]
Adding more details for a future contributor. 

Currently, our database looks like this https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=550121964

on postgres, google cloud.

We need to add a column for date created and date modified for each of these rows, so that we know when the page was created and last modified. Once that column is added, please provide and endpoint to the front end team so they can start using it.

**Comment by paulchrisluke** [comment]
@KennethA1000 another good one

**Comment by ctyar** [comment]
Fixed in https://github.com/ctyar/meredith-core/commit/6db826e3c91dc3741817ca415be121c8c7ff140d
