### ISSUE TITLE
Add endpoints for product & public modules

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#58]
https://www.figma.com/file/48dgLg97h5BxdmCkDgrMof/Meredith-Core-ER-Diagram?node-id=35%3A53160

These modules/tables should already be built. We need to ensure we have endpoints as well so the frontend team can build our cms.

Current:
https://stagingapi.whynot.earth/index.html

**Comment by atharva3010** [comment]
All that we'd require is the ability to change the data related to each page `/api/v0/pages/slug/{companySlug}/{pageSlug}` and to be able to add new pages by appending to the categorical sorted list here `/api/v0/pages/slug/{companySlug}/categories/by-name/{categoryName}`

**Comment by paulchrisluke** [comment]
note. I am changing this issue title and making it relative to volkswagen's needs rather than just "everything". CMS is found here: https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637

we will need lots of endpoints for the cms to write and deploy emails. I don't know if we should keep this a single issue or break it out into smaller ones? 

Either way. This issue is for volkswagen and is our current highest priority. The front end team will need these endpoints in a nice list so they can start making the cms asap

**Comment by paulchrisluke** [comment]
I should just close this issue its a mess. Making a new one for product module
