### ISSUE TITLE
Cookie SameSite in new versions of Chrome

### ISSUE THREAD

**Issue by mort3za** [whynotearth/meredith-core#62]
In Chrome v79 I get these warnings:

A cookie associated with a cross-site resource at https://whynot.earth/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

A cookie associated with a cross-site resource at https://stagingapi.whynot.earth/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

This seems will break our authentication system, so we should fix it soon.

**Comment by StrangeWill** [comment]
https://github.com/whynotearth/meredith-core/blob/529881e7abb3d3ba77f79bbe6d6c656b50c6c90b/WhyNotEarth.Meredith.App/Startup.cs#L126

Hmm, may need to check on some stuff.

**Comment by StrangeWill** [comment]
Got till Feb 2020 to fix this on the API ends of things.

@mort3za do you have a site I can test this from?

**Comment by mort3za** [comment]
@StrangeWill The warning happens in https://develop.vkirirom.com/ too.  

![image](https://user-images.githubusercontent.com/510242/71825527-50226f00-30b1-11ea-8666-0fea260c159b.png)

![image](https://user-images.githubusercontent.com/510242/71825669-911a8380-30b1-11ea-8344-e2eecead6568.png)

**Comment by StrangeWill** [comment]
OK, configuration is right, just .NET Core hasn't been updated to 3.1 which accepts this behavior as per here: https://github.com/aspnet/Announcements/issues/390

See #65

**Comment by ctyar** [comment]
Closed with #100
