### ISSUE TITLE
Mark rooms as unavailable

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#72]
If a room is booked (cash or credit card) we need to remove that room from being able to be booked again on the same date.

If all rooms of a particular room type (say all pipe rooms) are fully booked on a particular day, that day should be marked as grey on the front end booking calendar, and not selectable.

**Comment by StrangeWill** [comment]
The first should already be the case, the second though needs to be done as part of the pricing API call.

**Comment by ctyar** [comment]
@StrangeWill is correct we do have the first part.
https://github.com/whynotearth/meredith-core/blob/39c2635e81bc15468e6f132e8f8e557a47e127bf/WhyNotEarth.Meredith/Hotel/ReservationService.cs#L31-L65

But not the second point:
https://github.com/whynotearth/meredith-core/blob/39c2635e81bc15468e6f132e8f8e557a47e127bf/WhyNotEarth.Meredith.App/Controllers/Api/v0/RoomTypeContoller.cs#L25-L40

**Comment by StrangeWill** [comment]
If @ctyar has the time, I'd say grab it and modify the prices to only return prices for available rooms.
