### ISSUE TITLE
configure single user account and subdomain structure JWT discussion

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#78]
Dropping this into an issue to make sure we discuss this at some point: 

@strangewill:
```
We stopped using JWT long ago when the requirement for cross-site sessions was added.
guess that's going away though
because users are no longer going to be cross-site
This was part of the whole "global platform, single identity" thing from all the marketing stuff @paulchrisluke was reading :V
but it introduces so many issues
The JWT and cookie auth flow aren't really much different though.
a bad/missing cookie should return 401, a bad/missing JWT token would return 401
we can add additional cross-site tracking though on top of the login stuff
but it'll be separate
```

@paulchrisluke:
```
I do like one user one identity across sites ... But that has less priority than actually making transactions. We can back into that down the line I suppose
```

StrangeWill:
```
t introduces a lot of very... interesting security implicatoins
Usually cross-site auth was oauth based flows and handshakes
ours was just 100% opaque and makes things like password resets spooky
Unless you came back to us for all account management
```

Paulchrisluke:

```
This is going to sound stupid. But if we made "my account" merediyh-core specific. Could we nest that content within the clients website? 

Like an iframe but betterb
Jumper.ai does something like this, they build the site and you get a subdomain like vkirirom.jumper.ai . Then you redirect to your ecommerce jumper site with a hyperlinked buy now button.

If you want your own instance, they white lable it and give you your own domain but jumper is still handling all that stuff
And a very much like that. From a sales perspective, it would be pretty easy to just sell us as the credit card and booking engine and let other hotel owners still use their own site but redirect us for all the booking and transactions
our competition out here is cloudbeds and https://www.travelanium.com/website-portfolio.html

They're horrible
```

**Comment by StrangeWill** [comment]
> Then you redirect to your ecommerce jumper site with a hyperlinked buy now button.

Yeah, we had discussed this before when discussing solutions to this problem, the first answer was that redirects were probably a no-go, but if that's back on the table it's easier... though Meredith is going to want it's own UI to do so, going basically off-site for auth, we _could_ def do that and that solves a massive amount of problems (along with our entire effort to silo users into sites). Also means that we handle password resets and whatnot.

**Comment by paulchrisluke** [comment]
I can make a ui, very simple.

perhaps for an immediate solution, we move the log in portion to the very end of the checkout flow, popping up after a successful transactions and before the thank you screen "save your info for next time by signing up" @mort3za ...at least that way we aren't hurting our conversion funnel live

In the meantime I'll design a ui and we can keep talking about this in discord.

**Comment by paulchrisluke** [comment]
I think we are going with JWT and don't need the ui for now. Closing unless I hear otherwise.
