### ISSUE TITLE
Stripe webhook delivery issues for https://api

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#79]
Hi there,

We’re contacting you because we’ve had some trouble sending requests to a webhook endpoint associated with your whynot.earth account in live mode. Webhooks are used to notify your server about events that happen in your Stripe account, such as a payout completing or an invoice being created. The failing webhook endpoint is https://api/v0/reservations/paymentintent/confirm.

You or someone on your team has added that endpoint in your Stripe webhook settings, which you can view and edit here: https://dashboard.stripe.com/account/webhooks.

Please note that in most cases a failing webhook does not impact your payments or payouts. However, if you use subscriptions we rely on your webhook endpoint to notify you of new invoices. These invoices may be delayed for up to three days if your webhook is unable to successfully receive them. If you use Checkout, you may be handling the `checkout.session.completed` event as part of your purchase fulfillment process as described here: https://stripe.com/docs/payments/checkout/fulfillment#webhooks. If you do, failure to handle these events may interfere with purchase fulfillment.

We’ve attempted to notify the endpoint 11 times since February 5, 2020 at 11:08AM. If this endpoint is important to your application, please try and fix the issue. If you do not need the webhook endpoint you can delete it from your Stripe webhook settings. We will stop sending notifications to your webhook by February 14, 2020 around 11:08AM.

Here is the summary of errors we have received when sending you webhooks:
* 11 requests had a TLS error, you can get a detailed analysis on your host's TLS configuration at: https://ssllabs.com/ssltest/analyze.html?d=api:443&hideResults=on.

You need to return anything between a HTTP 200 to 299 for the webhook to be considered successfully delivered.
For more details on the errors, you can find your events page here: https://dashboard.stripe.com/events.

You can also always review the history of webhooks and failed request logs right from your dashboard: https://dashboard.stripe.com/events.

For more in depth information about how to use webhooks, we recommend taking a look at our documentation: https://stripe.com/docs/webhooks.

Yours,

The Stripe team

**Comment by ctyar** [comment]
It seems our webhook URL is incomplete
We should fix it in [here](https://dashboard.stripe.com/account/webhooks)
The domain name is missing in the webhook `https://api/v0/reservations/paymentintent/confirm`

**Comment by paulchrisluke** [comment]
should it be this? 
`https://stagingapi.whynot.earth/api/v0/reservations/paymentintent/confirm`

**Comment by ctyar** [comment]
Yes

**Comment by paulchrisluke** [comment]
ok I made the change here but rollbar sent us some errors:

```
StripeException: Received event with API version 2019-12-03, but Stripe.net 27.20.0 expects API version 2019-05-16. We recommend that you create a WebhookEndpoint with this API version. Otherwise, you can disable this exception by passing `throwOnApiVersi
```

I think @StrangeWill sent you access to rollbar via email yesterday. Is that error something to be concerned about?





![image](https://user-images.githubusercontent.com/5694308/74086009-7b81ea80-4ab1-11ea-9b60-a481b021458d.png)

**Comment by ctyar** [comment]
Yeah I'm working on it
