### ISSUE TITLE
Copy Staging DB To Production

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#81]
Currently we are using staging on our live vkirirom.com site

The schemas between our production db and staging db is different, so we will need to schedule a migration time. Next weekend? Feb 14-16th sometime?

**Comment by paulchrisluke** [comment]
We need to remove the old production db
Copy the staging db
Switch the production meredith-core to use the production db

@ctyar can do this, but I don't know how we are handling access yet @StrangeWill ?

**Comment by StrangeWill** [comment]
Yep, he can do it, that's just done through the SQL credentials we have. You can create him his own set.

**Comment by paulchrisluke** [comment]
@StrangeWill can we schedule a time to get this done?

**Comment by StrangeWill** [comment]
Fixed  the title -- was really confusing because they _are_ separate.

**Comment by StrangeWill** [comment]
Copied, feel free to verify and close @paulchrisluke
