### ISSUE TITLE
move login flow to after checkout

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#87]
I think in general, introducing a social login before checkout needless obstructs the checkout flow. I'd like to move the social account stuff to after the checkout flow, in something that looks more like this:

![image](https://user-images.githubusercontent.com/5694308/74733702-7118db00-527f-11ea-864d-c16648839773.png)

I assume that would mean would would need to start building the user profile with the first question of email and not starting with the social profile? @StrangeWill @ctyar 

We can find other incentives to have users link their accounts... "sign up for notifications via sms, facebook, email (gmail)" etc. I would assume these notification linkages would be in the user area of meredith for integration of outbound marketing integrations like twilio for sms?

@mort3za for awareness, we have not finished the design of that pop-up yet. @atharva3010

**Comment by ctyar** [comment]
Doesn't this make the registration step optional? Because they can just leave at this step

**Comment by paulchrisluke** [comment]
Yes, that is correct!

**Comment by paulchrisluke** [comment]
@ctyar this is the next task, and should probably piggy back off the discussion we had on twitch today.

In general, I think limiting certain functions to public that is useful for all clients would be good, and then only do custom modules when we need it.

things I imagine in the public (core):

# page building (this does not include all our current fields, just an idea)
- title
- image
- slug
- description
- seo area (json)
- call to action form functions

# user management (single user profile for all meredith core sites)
- photos
- authorized accounts (facebook, gmail, email, etc)
- notification preferences (email, facebook, pwa notifications, sms, etc)
- single trackable profile which builds user data profile as we collect it

# stripe transaction stuff
- authorize stripe accounts to meredith core
- transactions 

# outbound marketing
- email integrations with sendgrid for inbound and outbound communications with the user profile above
- sms integretations with twilio for inbound and outbound communications with the user profile above
- chatbot integrations (maybe twilio, site pwa) for inbound and outbound communications with the user profile above
- google and facebook ad integrations to push outbound marketing ads (we want to track the spend here, so we can tellwe spent this much we made this much) TRACKING

# cms portion
- ability to add/move/change items within the database

# tracking
- maybe use segment for tracking needs we talked about today? Need to look into this. 

# translations (every site will need to have multi language ability)
- langauge translations for all text content

Then above that (example hotelmodule) we keep only stuff each module needs to stand alone. Like room types, price management, booking logic, deposit policies etc. 

Overall, this info is just as a reference when you are moving this user stuff around to refactor how we do user management and data building.

**Comment by ctyar** [comment]
In the reservation process, we should ask for the user's email address and create a user without a password and log in the user.
After finishing the reservation we give the user the option to connect his other accounts(Facebook, Google) but this is optional.
The hard part would be when a user comes a second time and tries the same thing with the same email. At this point if I find the user's email address I have to log in them.
Right now we don't have any endpoint that gives back any data so at worst a user can reserve a room with someone else's email address which is useless.
But if in future we add an endpoint that gives user data like `my trips` we have to limit these endpoints to only users that have completed email verification and also have a password.
What do you guys think?

**Comment by mort3za** [comment]
My suggestion:
----
User is not logged in:
  1. Create a user with random email address (like iwheisdjnwuiehfksjdhfiuwehf@example.com)
  2. Get user's email in contact info step without verification
  3. Send payment result to user's email and go to final step (thanks page)
  4. If user do an authentication step there, merge the anonymous user's data to the real account _and maybe remove the anonymous user_. But if user did not log in, do nothing else.

User is logged in with a real account:
  1. Don't get email in contact info page, don't do registration again and go to payment and thanks page.

User is logged in with a random email (through a previous reservation):  
 1. Let user to modify his email again in contact info step but **don't** register a new user with random email. So he can fix his previous mistake if any, and can keep the trips and data connected to one account.
 2. Send payment result to user's email and go to final step (thanks page)
 3. If user do an authentication step there, merge the anonymous user's data (new and old reservation data) to the real account _and maybe remove the anonymous user_. But if user did not log in, do nothing else.


In this way, we have the trips page for logged-in users (no matter what kind of user, real email or random), and we have no security concern or limitation in getting data that probably needs ACL, IDK. Also, we can suggest him to connect his data to a real account in other pages too (e.g. my trips page).

If _the user with random email_ logged out, his data is gone and can't access it normally.

The hard part probably is merging data of previous user and the new real account.

I need a way in frontend to detect these new type of users, maybe a flag in user data.

**Comment by paulchrisluke** [comment]
I think this is the right idea, I made a simple example of a user data and how we'd capture it:

https://docs.google.com/spreadsheets/d/1Sr9rFjr2rTZcnSh35dO7rFcFuZuoDWRzUcR8J-nFbhg/edit#gid=0

Basically, when first entering the site, assign a userID. As that userID profile is built, add data to that userID profile.

In the event that a duplicate userID enters the site and the email or name/phone is recognized, prompt the user "are you this person?" if yes, de-deuplicate that new userID into the old one, and merge the user data into that original userID.

The idea is a constant profile building and de-duplication process. In the event of a log out, start a new userID.
