### ISSUE TITLE
TESTS

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#95]
Not being able to log in went undetected for a while. Is there a way we can setup some basic tests to ensure our conversion funnel is monitored?

**Comment by StrangeWill** [comment]
Depends on where our failure exists:

1) We can stand up our APIs and check that they're doing dual-auth correctly
2) To test our sites requires a more proactive monitoring/testing of our sites (their own tests)
3) Ongoing monitoring requires more complex monitoring setups that you can script flows into (used to do with platforms like Nagios, there are probably better options today)

I know we added JWT support here: https://github.com/whynotearth/hotel-website-vkirirom.com/pull/424 I don't know if it was ever tested or confirmed as working. We kind of effectively just pushed out an auth change without testing.
